import Foundation

struct SettingsPlugin: AppPlugin {
    let descriptor = PluginDescriptor(
        id: "yc.settings",
        displayName: "Settings",
        version: .v1,
        feature: .settings,
        category: .core,
        isRemovable: false,
        summary: "Provides settings surface and legal links."
    )

    func makeHomeItems(container: AppContainer) -> [PluginHomeItem] {
        [
            PluginHomeItem(
                id: "settings-card",
                title: "Settings",
                subtitle: "Central surface generated by plugins",
                systemImage: "gearshape.2",
                route: .settings
            )
        ]
    }

    func makeSettingsItems(container: AppContainer) -> [PluginSettingsItem] {
        [
            PluginSettingsItem(id: "legal-privacy", title: "Privacy Policy", subtitle: "Open privacy policy", systemImage: "hand.raised", route: .legal(.privacy)),
            PluginSettingsItem(id: "legal-terms", title: "Terms of Use", subtitle: "Open terms", systemImage: "doc.text", route: .legal(.terms)),
            PluginSettingsItem(id: "legal-eula", title: "EULA", subtitle: "Apple standard EULA", systemImage: "checkmark.shield", route: .legal(.eula))
        ]
    }
}
